colbyfayock/next-wordpress-starter

package.json, src/components/PostList/index.js, src/lib/apolloClient.js, src/lib/postsql.js, src/pages/_app.js, src/pages/postlist.js, src/pages/posts/[slug].js, src/pages/postsql/[slug].js, yarn.lock
I haven't replaced the REST logic for now but have created complementary graphql equivalents.
To test:
- Make sure you have wpgraphql installed on your WP instance (https://www.wpgraphql.com/) - happy to support with this if necessary.
- Add a .env variable `GRAPHQL_URI=` (once you've set up WPGraphQL this will be WP_ROOT/graphql
- Start Next
- Navigate to /postlist
- You should a list of all the posts on your WP instance
- Click on each of the posts
- This should bring you to a properly rendered page for each post.
=> GraphQL POC

src/components/Content/Content.js, src/components/Content/Content.module.scss, src/components/Content/index.js, src/components/Layout/Layout.js, src/components/Metadata/Metadata.js, src/components/Metadata/Metadata.module.scss, src/components/Metadata/index.js, src/components/Nav/Nav.js, src/components/Nav/Nav.module.scss, src/components/PostCard/PostCard.js, src/components/PostCard/PostCard.module.scss, src/data/pages.js, src/data/routes.js, src/data/wordpress.js, src/hooks/use-apollo-client.js, src/lib/apollo-client.js, src/lib/pages.js, src/lib/posts.js, src/lib/postsql.js, src/pages/[slug].js, src/pages/_app.js, src/pages/postlist.js, src/pages/posts/[slug].js, src/pages/postsql/[slug].js, src/styles/globals.scss, src/styles/pages/Post.module.scss
This adds support for basic pages using the same method we're currently using for posts.
All top level pages are made available at the root, as in, slug `about` as a top level would be available at /about
This doesn't yet take into consideration child pages, which will be addressed as we start to build out the documentation
This also adds a mechanism for adding items to the navigation menu
It turns out that the API doesn't support grabbing the menu by default, which is a bummer, so I'm taking advantage of the "menu order" property, and if that's explicitly set (not 0), we include those as part of the navigation menu
This might be suited to flesh out more later, whether an add-on tutorial or something. There's a separate issue already open to explore menus
=> Page Support

README.md, docs/exposing-data.md
This is related to issue #4 
This is documentation, as research suggests that the best way to do this is configuring the Headless WordPress to expose the data in a consumable way.
To test:
- Try to run through the documentation yourself
- Does it make sense? Where did you get confused? How could we make it better.
=> Adds the WP/ACF/GraphQL documentation

src/components/Metadata/Metadata.js
If, for any reason, a post does not have a category associated, it breaks at Metadata component trying to get the slug.
It just adds a check if at least there is one category in order to mount the categories **list item** or not.
|Error                    |
| ---------------------------------- |
| ![uncategorized-error](https://user-images.githubusercontent.com/50624358/95867140-35b3ab00-0d3f-11eb-8db2-dd850e74646b.png) |
=> Fix uncategorized post bug

src/lib/site.js
When retrieving data from WordPress REST API is checked if the site title contains any HTML special character, and if is 
the case it replaces by its Unicode version. I found relevant to check: [ ' | " | & ], as it can appear in a site title. 
Reference: https://dev.w3.org/html5/html-author/charref
|Before                   | After
| ---------------------------------- | ---------------------------------- |
| ![before](https://user-images.githubusercontent.com/50624358/95922381-894ae680-0d89-11eb-8169-3296f1b7fb88.png)| ![after](https://user-images.githubusercontent.com/50624358/95922393-8f40c780-0d89-11eb-8177-3f1500f3628e.png) |
Fixes #40
=> Fixes Issue #40

.github/workflows/checks.yml
Currently, `yarn install` installs always the newest dependencies without respecting `yarn.lock`.
This makes build not easily reproducible and might trigger false positives errors in PRs.
Apart from that, reworked the Actions file a bit to remove unnecessary `npm install -g yarn` as well as testing for both NodeJS 12.x and 14.x
=> Improve Github Actions to respect yarn.lock

package.json, src/components/Metadata/Metadata.js, src/lib/users.js, src/pages/authors/[slug].js, yarn.lock
Fixes #35
It now creates author page using a parameterize version of the name (i.e. /authors/john-doe) instead of using the author slug coming from WP API. It adds two new functions at users lib, maintaining previous two functions (authorPathBySlug and getUserBySlug) , in case is needed in the future.
=> Add Author page URL using name

plugins/search-index-compiler.js, plugins/search-index.js
I noticed when adding some logging to debug #37 that this plugin runs a billion times. This is an attempt to reduce it down to 1 time for production builds.
We're using the `run` and `watchRun` hooks again for webpack. The reason being I'm able to find an options object in both instances where I can check if we're on the `main` compilation and only run this process once when we see that
This is resulting in a single run for production build 🙌 
This still runs multiple times during development builds but I think that's okay. It'll run every time a change is made and recompiled.
I'm not sure if this actually fixes the issue related to #37, but I'm going to mark it as such and we can loop back if it pops back up as it should be much easier to debug with the logging i added and the fact it …
=> Search Index Compiler Run Check

plugins/search-index-compiler.js, plugins/util.js
Fixes #66
Changes the search index compiler plugin to use GraphQL. ~~It uses [graphql-request](https://github.com/prisma-labs/graphql-request).~~
=> Change Search Index Compiler to use GraphQL

next.config.js, plugins/util.js, src/lib/apollo-client.js, src/lib/site.js
Fixes #83
It cleans last trailing slash at WORDPRESS_HOST env variable to not break graphql queries.
=> Fix final trailing slash breaking at WORDPRESS_HOST

.gitignore, next.config.js, plugins/plugin-compiler.js, plugins/sitemap.js, plugins/util.js
Fixes #27
It adds a sitemap generator plugin. Some considerations I made, open to be discuss:
- The plugin creates a sitemap with both **pages** (including homepage) and **posts**. I consider **not** to include **author** and **category** pages to avoid duplicate content.
- Pages (excluding homepage) are included with a lower priority than the posts, `0.3`. By default all urls have `0.5` of priority. 
- Is included an aditional function to generate a `robots.txt` file: By default is always generated. However, if someone passed in `outputDirectory` to nextConfig is checked if is a `public` subfolder in order to resolve sitemap URL. If the passed `outputDirectory` not correspond to a public subfolder then the robots.txt is not generated. (at _resolvePublicPathname()_ ).
> For example, if a …
=> Add sitemap plugin and robots.txt

src/lib/json-ld.js, src/pages/[slug].js, src/pages/authors/[slug].js, src/pages/categories.js, src/pages/categories/[slug].js, src/pages/index.js, src/pages/posts.js, src/pages/posts/[slug].js, src/pages/search.js, src/templates/archive.js
It creates JSON-LD support by adding the json-ld script to the React Helmet. There are 4 main structures:
1.- **ArticleJsonLd** - For blog posts
2.- **WebsiteJsonLd** - For index (with integrated searchbox)
3.- **AuthorJsonLd** - For authors page
4.- **WebpageJsonLd** - This is the most generic one. Is used in all the rest of pages.
I've checked results with different values at https://search.google.com/structured-data/testing-tool, and I believe is working fine.
For Article the image appears to be a recommended/important field and not every time a post has a _featuredImage_, so when #13 is solved would be great to include it as the default image for the post in case there is no _featureImage_.
Fixes #92
=> Add JSON-LD support for all pages

README.md, next.config.js, plugins/feed.js, plugins/plugin-compiler.js, plugins/search-index.js, plugins/sitemap.js, plugins/util.js, src/lib/apollo-client.js, src/lib/site.js
WPGraphQL supports changing the default /graphql, meaning, doing so would break the starter
I originally was going to add only support for that, but decided to allow just the wordpress_host for now, maybe we can revisit if that's not desired
This means, you can now either set `WORDPRESS_GRAPHQL_ENDPOINT` as the full endpoint or pass in `WORDPRESS_HOST` as you can today and either should work
Fixes #79
=> Flexible WPGraphQL Endpoint

next.config.js, plugins/feed.js, plugins/plugin-compiler.js, plugins/search-index.js, plugins/sitemap.js, plugins/util.js
Updates plugin message log: By default, without errors, one line per plugin will print reporting successful operation. It is possible to pass a boolean variable, `verbose`, at _next.config.js_ set to **true** to print previous informational messages.
Also errors are now handled regardless of message logging. Errors wont block the process as they are handled by try-catch.
One extra function is added to print colors at console, making easier to understand info messages from errors.
|Info                    |Errors
| ---------------------------------- | ---------------------------------- |
| ![shot](https://user-images.githubusercontent.com/50624358/100639277-bb051600-3313-11eb-8873-e355ba274c81.png) | ![error](https://user-images.githubusercontent.com/50624358/100639296-c0faf700-3313-11eb-88 …
=> Add verbose option for plugins

src/lib/posts.js, src/pages/posts/[slug].js, src/styles/pages/Post.module.scss
It adds at `Post` footer a list of related posts links (by post category). 
The default count of links is set to 5, but the function can receive a new count to show a custom number. The function filters the related posts to exclude the current post.
Fixes #117
=> Add related posts links to post page

src/pages/404.js, src/styles/pages/404.module.scss
It adds a custom 404 page, wrapped inside the Layout component with a homepage link. 
#Fixes #133
=> Add a custom 404 page

next.config.js, src/components/Pagination/Pagination.js, src/components/Pagination/Pagination.module.scss, src/components/Pagination/index.js, src/lib/posts.js, src/pages/index.js, src/pages/posts/page/[page].js, src/templates/archive.js
The variable `POSTS_PER_PAGE` at _next.config.js_ controls the number of posts render at each page. The component has been added to `template/archive` and is being used at `posts/` and `posts/page/[page]`.  The dynamic paths are created at [page].js. 
From SEO perspective, it is used rel="next" and rel="prev" (conditionally) and for the first page the canonical link to posts/ (because `posts/page/1` and `posts/` will have duplicated content).
There is one aditional function `sortStickyPosts` to make the code reusable and converting it into a pure function avoiding possible side effects.
I thought that for smaller screens or mobile devices (under 768px) would be a good idea to hide the page links and leave only the next/prev links. Totally open for any feedback/changes here.
|Dektop …
=> Add pagination component

README.md, next.config.js, src/components/Nav/Nav.js, src/data/menus.js, src/lib/menus.js, src/lib/pages.js, src/pages/_app.js
This adds the ability to create new locations from within the WordPress Menus system and use them within the project.
It starts off by using the default PRIMARY navigation from WordPress, and if a menu is set to that location, uses it for the top level navigation.
Otherwise, it just displays all of the top level pages, which needless to say won't support a huge list of them.
The menus do not support children at this time.
By default, inside `next.config.js`, the primary menu is set to the ID:
```
MENU_LOCATION_NAVIGATION: 'PRIMARY',
```
But can be changed if would prefer to use another location, making this work without a location and easy to add.
Fixes #148
Fixes #7
=> Dynamic Navigation Menu

src/lib/site.js, src/lib/util.js
If a user does not have the Yoast plugin support enabled, the description meta tag is pulled directly from the API (description field). As a user can write descriptions using spaces or paragraphs, the created tags could possibly end with that extra spaces as well.  One example could be an author writing a bio using paragraphs, that may end with meta tags replicating that spaces (image below). Also that text is replicated for `og.description` and `twitter.description`.
It is added a function that removes extra spaces at `lib/util`. As title doesnt seem to be a field where this can happen, it is applied only for description.
|Before                    |
| ---------------------------------- |
|  ![before-meta](https://user-images.githubusercontent.com/50624358/116931759-cc8e7900-ac37-11eb-848 …
=> Add description sanitization (extra spaces) to metadata

next.config.js, plugins/feed.js, plugins/plugin-compiler.js, plugins/search-index.js, plugins/sitemap.js, plugins/socialImages.js, src/lib/apollo-client.js, src/lib/categories.js, src/lib/pages.js, src/lib/posts.js
Removes `WORDPRESS_HOST` as an option in favor of `WORDPRESS_GRAPHQL_ENDPOINT`
Added to the existing warning if a host doesn't exist, just mentioning that this won't work.
Fixes https://github.com/colbyfayock/next-wordpress-starter/issues/151
=> Removes WORDPRESS_HOST as an environment variable option

.gitignore, src/components/FeaturedImage/FeaturedImage.module.scss
While testing the build for #178, I found the following warning on console:
It seems like this operator [has been deprecated](https://sass-lang.com/documentation/breaking-changes/slash-div) and the recommended operator in replace is [math.div()](https://sass-lang.com/documentation/modules/math#div)
I also added the line to ignore VSCode settings.
=> Replace sass '/' deprecated operator with math.div

src/hooks/use-search.js, src/lib/search.js, src/pages/_app.js, src/pages/search.js, src/templates/archive.js
Updates the search index to get fetched in the browser instead of imported. This is to help resolve errors when trying to build a fresh copy.
Moved this logic to the _app and providing the data and interface in global context to avoid multiple and conflicting indexes
Fixes https://github.com/colbyfayock/next-wordpress-starter/issues/178
=> Clientside Search

README.md
It adds the steps to configurate the ESLint extension in VSCode at README.
Don't remember if you agreed to have this at the README or if it was preferable to have it as a post... Feel free to close it or change anything in the description. I can save the text for the future post format, so no problem if you think is better to close this =)
=> Add ESLint extension config info to README

src/lib/site.js
It fixes the meta name to make Twitter summary cards work.
That was hard to catch , I was making all kind of tests not related to the property name 😆 . 
@colbyfayock could you please check the og images of https://next-wordpress-starter.spacejelly.dev/ it seems that they have been created incorrectly: https://next-wordpress-starter.spacejelly.dev/images/og/voluptas-in-nemo-eaque-tempora-sit-quisquam.png
Probably when I sent that PR with the SASS operator change that failed?
Fixes #174
=> Fix twitter card summary image

src/components/Nav/Nav.js, src/components/Nav/Nav.module.scss, src/hooks/use-search.js
Disables the search button toggle in the navigation until the search is loaded.
RE: https://github.com/colbyfayock/next-wordpress-starter/issues/178#issuecomment-852330016
=> Search State Loading

next.config.js, src/data/posts.js, src/lib/posts.js, src/pages/posts/page/[page].js
It updates the variable post per page querying `readingSettingsPostsPerPage` from WP. If the previous `POST_PER_PAGE` env variable is set, it will be used but displaying a warn reporting that it has been deprecated.
Previous thread: #176
Fixes #171
=> Update post lib to use WP posts per page value

.eslintrc.js
Disables the Next Image component rule (warning) until it is solved how to use it at build time.
Related: #199
=> Disable Next Image component rule for ESLint

src/data/categories.js, src/lib/categories.js
Queries `QUERY_CATEGORY_BY_SLUG` and `QUERY_CATEGORY_SEO_BY_SLUG` are querying a list of categories, and then picking the first item.
But WPGraphQL can already query a single category by its slug: `{ category(id: $slug, idType: SLUG) { id } }`
So this PR replaces it
=> Replaced field "categories" with "category" when querying a single category by slug

plugins/util.js, src/data/categories.js, src/data/menus.js, src/data/posts.js, src/lib/posts.js, src/pages/categories/[slug].js, src/pages/posts/[slug].js
The following fields are deprecated:
- `Post.postId`
- `Category.categoryId`
So I replaced them with field `databaseId`.
Also `Menu.menuId` is deprecated, but I noticed that it is not used anywhere, then I removed the field from the query.
=> Replaced deprecated fields

src/lib/menus.js
Currently, the logic to search for the menu called `PRIMARY` via `includes()` is case sensitive.
However, in WordPress the menu is called `primary`, in lower case (at least for the Twenty Twenty-One theme). I do not know why WPGraphQL is returning it in uppercase, if by design or accident, but I have the impression it's not right.
So this PR makes the search case insensitive, so `PRIMARY` can be found always, even if GraphQL retrieves it as `primary`
=> Make the menu's search by location `PRIMARY` case insensitive

src/lib/menus.js
When searching for the menu `PRIMARY`, if the menu is not the first one in the list from the response from GraphQL, then the menu will not be found. That's because `location.shift()` will make `location` be empty after the 1st item, and then the comparison will always be against the empty array for all other items in the list.
To fix it, I first duplicated `location` into `searchLocations` and then compare against that.
=> Fixed issue: `PRIMARY` menu is not found if it's not the 1st item in list

src/components/Footer/Footer.js
Due to using the Next.js Link component for the Sitemap and RSS Feed, Next.js is trying to do a page lookup which is unavailable given they're externally generated and in the public folder.
This converts them to standard anchor tags, treating them like external links, to avoid the issue.
Fixes https://github.com/colbyfayock/next-wordpress-starter/issues/317
=> Convert Sitemap and Feed XML links to standard anchors

src/data/pages.js, src/data/posts.js, src/lib/pages.js, src/lib/posts.js, src/pages/[slugParent]/[[...slugChild]].js, src/pages/_app.js, src/pages/authors/[slug].js, src/pages/categories/[slug].js, src/pages/index.js, src/pages/posts.js, src/pages/posts/[slug].js, src/pages/posts/page/[page].js
* Reduces the data being passed in from props for Posts and Pages by creating different types of queries based on the needs
* Uses query fragments to help avoid having to repeat the same fields for each query
* Updates Related Posts to try to fallback to another category if the first category doesnt produce results
Reduced the homepage from 45kb to 5.7kb with the demo
Post page example from 31.6 kbto 11.7kb
Should help speed up builds a bit too
=> Reducing queried data where not needed

src/lib/posts.js, src/pages/posts/[slug].js
Resolves a bug when getting related posts where we weren't properly checking for the existence of data before trying to use a property.
Fixes #341
=> Fix related posts bug when empty

next.config.js, src/data/categories.js, src/data/menus.js, src/data/site.js, src/data/users.js, src/lib/apollo-client.js, src/pages/[slugParent]/[[...slugChild]].js, src/pages/authors/[slug].js, src/pages/categories/[slug].js, src/pages/posts/[slug].js, src/pages/posts/page/[page].js
* Updates all dynamic routing to use `blocking` as the fallback for non-prerendered paths
* Removes all Category, Author, and Pagination pages from prerendering paths
* Pre-renders only the first 5 most recent posts
=> On-Demand Page Rendering

README.md
Fixed error for `ApolloError: Response not successful: Received status code 404`
With help from [here](https://www.wpgraphql.com/docs/interacting-with-wpgraphql#http-post-requests)
Fixes #591
=> fix(app): fix for Apollo error
